show databases;
use classicmodels;
show tables;
desc customers;
select customername,country from customers; 
select customername,country from customers group by country; 
select country,count(*) from customers;
select country,count(*) from customers group by country;
desc orderdetails;
select ordernumber,sum(quantityordered) from orderdetails group by ordernumber;
select ordernumber,sum(quantityordered) from orderdetails where ordernumber=10425 group by ordernumber ;
select sum(quantityordered) from orderdetails where ordernumber=10425;
desc payments;
select customernumber,sum(amount) from payments group by customernumber;
select sum(amount) from payments where customernumber=458;
select country,state,count(*) from customers group by country; /*here only one state will be there corresponding to a country and the state that will be decied by first come first serve basis*/
select country,state,count(*) from customers group by country,state;
select paymentdate,sum(amount) from payments where customernumber=473 group by paymentdate;
select sum(amount) from payments where customernumber=473 and paymentdate='2003-10-27';
select country,sum(creditlimit) from customers group by country having sum(creditlimit)>100000;
select country,sum(creditlimit) from customers group by country having sum(creditlimit)>100000 order by sum(creditlimit);
select country,sum(creditlimit) from customers group by country having sum(creditlimit)>100000 order by country;
select country,sum(creditlimit) from customers group by country having sum(creditlimit)>100000 order by sum(creditlimit) desc;
desc products;
select productname,productline,quantityinstock,buyprice,msrp from products where productline in ('motorcycles','classic cars','vintage cars') order by buyprice;
select productname,productline,quantityinstock,buyprice,msrp from products where productline in ('motorcycles','classic cars','vintage cars') and quantityinstock>8000  order by buyprice limit 5 ;
select productname,productline,quantityinstock,buyprice,msrp from products where productline not in ('motorcycles','classic cars','vintage cars') and quantityinstock>8000  order by buyprice limit 5 ;
select productname,productline,quantityinstock,buyprice,msrp from products where productline!='motorcycles' and productline!='vintage cars' and productline!='classic cars' and quantityinstock>8000  order by buyprice;
desc employees;
select employeenumber,jobtitle from employees where jobtitle in ('president','vp sales');
select employeenumber,reportsto from employees where reportsto not in (1002,1056) order by employeeNumber;
select productname,productline,quantityinstock,buyprice,msrp from products where quantityinstock between 4000 and 7000 order by quantityinstock desc;
select productline,msrp from products where productline!='ships' and productline!='planes' and msrp between 50 and 90;
select firstname,lastname from employees where reportsto=1143 and firstname like 'l%';
select customername,phone from customers where customername like '%to\-mo%';
select customers.customername,orders.ordernumber from customers inner join orders on customers.customernumber=orders.customerNumber order by customername;
desc orders;
desc orderdetails;
desc customers;
select orders.ordernumber,sum(orderdetails.priceeach) from orders inner join orderdetails on orders.ordernumber=orderdetails.ordernumber where orders.customernumber=128 group by orders.ordernumber;
select * from orders inner join orderdetails on orders.ordernumber=orderdetails.ordernumber where orders.customernumber=128;
select sum(orderdetails.priceeach),orders.ordernumber,customers.customername from orderdetails inner join orders on orderdetails.ordernumber=orders.ordernumber inner join customers on orders.customernumber=customers.customernumber group by customers.customername;
select count(*) from payments left join customers on payments.customernumber=customers.customernumber;